---
- name: Install Go and Hugo
  hosts: localhost
  become: yes
  vars:
    go_version: "1.21.4"
    go_tarball: "go{{ go_version }}.linux-amd64.tar.gz"
    go_url: "https://go.dev/dl/{{ go_tarball }}"
  tasks:
    - name: Remove existing Go installation
      ansible.builtin.file:
        path: /usr/local/go
        state: absent

    - name: Download Go tarball
      ansible.builtin.get_url:
        url: "{{ go_url }}"
        dest: "/tmp/{{ go_tarball }}"
        mode: '0755'

    - name: Extract Go tarball
      ansible.builtin.unarchive:
        src: "/tmp/{{ go_tarball }}"
        dest: "/usr/local"
        remote_src: yes
      args:
        creates: "/usr/local/go/bin/go"

    - name: Install Hugo
      ansible.builtin.shell:
        cmd: go install -tags extended github.com/gohugoio/hugo@latest
      environment:
        PATH: "{{ ansible_env.PATH }}:/usr/local/go/bin"
      become_user: "{{ ansible_user_id }}"
