---
- name: System Update and Cleanup Playbook
  hosts: all
  become: yes

  tasks:
    - name: Update all apt packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: full
        autoremove: yes
        autoclean: yes

    - name: Perform a distribution upgrade
      ansible.builtin.apt:
        update_cache: yes
        upgrade: dist

    - name: Refresh snap packages
      community.general.snap:
        classic: yes
        name: "*"
        state: latest
      ignore_errors: yes

- name: Install Basic Packages
  hosts: localhost
  become: yes
  tasks:
    - name: Install basic packages
      ansible.builtin.apt:
        name:
          - make
          - build-essential
        state: present
