name: Test Playbook

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Install Ansible
      run: sudo apt install ansible

    - name: Run Ansible playbooks
      run: make all
